apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-service'
        static_configs:
          - targets: ['10.96.78.235:5000/metrics']  # Replace with your actual service and port
